CREATE TABLE student (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR (64) NOT NULL DEFAULT "",
    PRIMARY KEY (id)
);

CREATE TABLE course (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR (64) NOT NULL DEFAULT "",
    PRIMARY KEY (id)
);