load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "coding_test",
    srcs = glob(["coding_test.cc"]),
    deps = [
            "@com_google_googletest//:gtest_main",
    ],
)
